name: Basic CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4

      - name: Python instellen
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Dependencies installeren
        run: pip install -r requirements.txt

      - name: Tests uitvoeren
        run: python -m pytest -v

      - name: Docker image bouwen
        run: docker build -t devops-basic-api:${{ github.sha }} .
